[mysqldatabase]
ip=192.168.3.45
username=liurui
password=usci9liurui
webdbname=usciweb
vcfdbname=uscivariantdata
ghostdbname=uscivariantdata_tmp
genomeinfodbname=genomebasicinfo
pekingduckchromtable=pekingduckchrominfo
D2Bduckchromtable=D2Bduckchrominfo
TranscriptGenetable=pekinduckmiRNA_Transcript
KB743256_1=KB743256_1
scriptdir=/USCIMD/usr/liurui/pipeline
outgroupVCFBAMconfig_beijingref=/home/liurui/data/config/BJ/fanyaBJ.VCFBAMconfig;/home/liurui/data/config/BJ/taihugooseBJ.VCFBAMconfig
beijingreffa=/home/liurui/databases/Anas_platyrhynchos.BGI_duck_1.0.dna_sm.toplevel.fa
pathtoPython=python
