[mysqldatabase]
ip=10.2.48.241
username=root
password=1234567
webdbname=ninglabweb
vcfdbname=ninglabvariantdata
ghostdbname=ninglabvariantdata_tmp
genomeinfodbname=genomebasicinfo
pekingduckchromtable=pekingduckchrominfo
D2Bduckchromtable=D2Bduckchrominfo
TranscriptGenetable=pekinduckchromTranscript
KB743256_1=KB743256_1
outgroupVCFBAMconfig_beijingref=/home/bioinfo/liurui/data/config/fanya.VCFBAMconfig;/home/bioinfo/liurui/data/config/taihugoose.VCFBAMconfig
beijingreffa=/home/bioinfo/liurui/databases/Anas_platyrhynchos.BGI_duck_1.0.dna_sm.toplevel.fa
pathtoPython=/home/bioinfo/liurui/software/Python-3.3.3/python
