[mysqldatabase]
ip=192.168.3.6
username=root
password=12345678
webdbname=autodemoweb
vcfdbname=fyyjvariantdata
ghostdbname=fyyjvariantdata_tmp
genomeinfodbname=genomebasicinfo
pekingduckchromtable=pekingduckchrominfo
D2Bduckchromtable=D2Bduckchrominfo
TranscriptGenetable=pekinduckmiRNA_Transcript
KB743256_1=KB743256_1
scriptdir=/home/lrui/WebsysController
outgroupVCFBAMconfig_beijingref=/ifs1/User/lrui/data/duckproject/configfile/fanyaBJ.VCFBAMconfig;/ifs1/User/lrui/data/duckproject/configfile/taihugeeseBJ.VCFBAMconfig
beijingreffa=/ifs1/User/lrui/database/Anas_platyrhynchos.BGI_duck_1.0.dna_sm.toplevel.fa
pathtoPython=python
